set(TARGET tokenize_demo)
add_executable(${TARGET} tokenize_demo.cpp)
target_include_directories(${TARGET} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../include)
target_link_libraries(${TARGET} PRIVATE tokenizer)
target_compile_features(${TARGET} PRIVATE cxx_std_11)
INSTALL(TARGETS tokenize_demo DESTINATION demo)
