import os
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com/")
import re
import sys
from collections import OrderedDict

import numpy as np
import torch


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PYTHON_ROOT = os.path.dirname(SCRIPT_DIR)

if PYTHON_ROOT not in sys.path:
    sys.path.insert(0, PYTHON_ROOT)


def resolve_path(path, base_dir=PYTHON_ROOT):
    if os.path.isabs(path):
        return path
    return os.path.normpath(os.path.join(base_dir, path))


def ensure_parent_dir(path):
    out_dir = os.path.dirname(path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)


def prepare_qwen_tts_import():
    external_repo = resolve_path("../../../../Qwen3-TTS")
    if external_repo not in sys.path:
        sys.path.insert(0, external_repo)

    try:
        from qwen_tts import Qwen3TTSModel
        return Qwen3TTSModel
    except ImportError as exc:
        raise ImportError(
            "Failed to import qwen_tts.Qwen3TTSModel. "
            "Please make sure the Qwen3-TTS repository exists or qwen_tts is installed."
        ) from exc


def format_float_c(x):
    return "{:.8e}f".format(x)


def parse_existing_header(header_path):
    if not os.path.exists(header_path):
        return OrderedDict()

    with open(header_path, "r", encoding="utf-8") as file_obj:
        content = file_obj.read()

    pattern = re.compile(r'\{"([^"]+)",\s*\{(.*?)\}\s*\}', re.DOTALL)
    entries = OrderedDict()
    for match in pattern.finditer(content):
        speaker_name = match.group(1)
        values_text = match.group(2)
        values = []
        for item in values_text.replace("\n", " ").split(","):
            item = item.strip()
            if not item:
                continue
            if item.endswith("f") or item.endswith("F"):
                item = item[:-1]
            values.append(float(item))
        entries[speaker_name] = values
    return entries


def dump_embeddings_to_header(embeddings_map, out_path, items_per_line=8):
    lines = []
    lines.append("#pragma once")
    lines.append("#include <unordered_map>")
    lines.append("#include <vector>")
    lines.append("#include <string>")
    lines.append("")
    lines.append("// Auto-generated by export_speaker_embed_hpp.py")
    lines.append("")
    lines.append("const std::unordered_map<std::string, std::vector<float>> speaker_embeddings = {")

    num_items = len(embeddings_map)
    for idx, (speaker_name, values) in enumerate(embeddings_map.items()):
        suffix = "," if idx < num_items - 1 else ""
        lines.append('  {{"{}", {{'.format(speaker_name))
        formatted = [format_float_c(float(v)) for v in values]
        for i in range(0, len(formatted), items_per_line):
            chunk = formatted[i:i + items_per_line]
            lines.append("    " + ", ".join(chunk) + ",")
        lines.append("  }}" + suffix)

    lines.append("};")
    lines.append("")

    ensure_parent_dir(out_path)
    with open(out_path, "w", encoding="utf-8") as file_obj:
        file_obj.write("\n".join(lines))


def build_model(args):
    Qwen3TTSModel = prepare_qwen_tts_import()

    if args.modelscope:
        from modelscope import snapshot_download
        model_path = snapshot_download(args.model_path)
    else:
        model_path = resolve_path(args.model_path)

    model = Qwen3TTSModel.from_pretrained(
        model_path,
        device_map="cpu",
        dtype=torch.float32,
    )
    return model


def export_speaker_embed_hpp(model, args):
    output_path = resolve_path(args.output_path)
    speaker_name = args.speaker_name

    prompt_items = model.create_voice_clone_prompt(
        ref_audio=args.ref_audio,
        ref_text=None,
        x_vector_only_mode=True,
    )
    if not prompt_items:
        raise RuntimeError("create_voice_clone_prompt returned empty prompt_items")

    embedding = prompt_items[0].ref_spk_embedding
    values = embedding.detach().cpu().numpy().astype(np.float32).reshape(-1).tolist()

    embeddings_map = parse_existing_header(output_path)
    embeddings_map[speaker_name] = values
    dump_embeddings_to_header(embeddings_map, output_path, items_per_line=args.items_per_line)

    print("[OK] wrote: {}".format(output_path))
    print("[INFO] speaker_name: {}".format(speaker_name))
    print("[INFO] embedding shape: {} numel={}".format(tuple(embedding.shape), embedding.numel()))


if __name__ == "__main__":
    from argparse import ArgumentParser

    parser = ArgumentParser(description="Export Qwen3-TTS speaker embedding header")
    parser.add_argument(
        "--model_path",
        type=str,
        help="model path or name",
        required=False,
        default="../../../../CKPT/Qwen3-TTS-12Hz-1.7B-Base",
    )
    parser.add_argument(
        "--ref_audio",
        type=str,
        help="reference audio path",
        required=False,
        default="https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen3-TTS-Repo/clone_2.wav",
    )
    parser.add_argument(
        "--speaker_name",
        type=str,
        help="speaker name written into qwen3tts_speaker_embed.h",
        required=False,
        default="custom_test",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        help="output header path",
        required=False,
        default="../models/embeds/qwen3tts_speaker_embed.h",
    )
    parser.add_argument(
        "--items_per_line",
        type=int,
        help="number of float items per line in generated header",
        required=False,
        default=8,
    )
    parser.add_argument("--modelscope", action="store_true", help="Whether download model from www.modelscope.cn")

    args = parser.parse_args()
    model = build_model(args)
    export_speaker_embed_hpp(model, args)
